"""create patient invitations

Revision ID: 14d35a334950
Revises: 4b8513511766
Create Date: 2026-09-03 15:22:45.597417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d35a334950'
down_revision: Union[str, Sequence[str], None] = '4b8513511766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('verification_code_hash', sa.String(length=255), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('created_by_doctor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_uses', sa.Integer(), server_default='1', nullable=False),
    sa.Column('used_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_verification_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('failed_verification_attempts >= 0', name='ck_invitation_failed_attempts_nonnegative'),
    sa.CheckConstraint('max_uses > 0', name='ck_invitation_max_uses_positive'),
    sa.CheckConstraint('used_count <= max_uses', name='ck_invitation_used_count_within_limit'),
    sa.CheckConstraint('used_count >= 0', name='ck_invitation_used_count_nonnegative'),
    sa.ForeignKeyConstraint(['created_by_doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_invitations_created_by_doctor_id'), 'patient_invitations', ['created_by_doctor_id'], unique=False)
    op.create_index(op.f('ix_patient_invitations_encounter_id'), 'patient_invitations', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_patient_invitations_patient_id'), 'patient_invitations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_invitations_token_digest'), 'patient_invitations', ['token_digest'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_invitations_token_digest'), table_name='patient_invitations')
    op.drop_index(op.f('ix_patient_invitations_patient_id'), table_name='patient_invitations')
    op.drop_index(op.f('ix_patient_invitations_encounter_id'), table_name='patient_invitations')
    op.drop_index(op.f('ix_patient_invitations_created_by_doctor_id'), table_name='patient_invitations')
    op.drop_table('patient_invitations')
    # ### end Alembic commands ###
