"""create encounters and patient ownership

Revision ID: 4b8513511766
Revises: 172174607c5d
Create Date: 2026-08-30 19:49:18.524862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b8513511766'
down_revision: Union[str, Sequence[str], None] = '172174607c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_code', sa.String(length=32), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('display_label', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounters_doctor_id'), 'encounters', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_encounters_encounter_code'), 'encounters', ['encounter_code'], unique=True)
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    with op.batch_alter_table('patients') as batch_op:
        batch_op.add_column(sa.Column('patient_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('responsible_doctor_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_patients_patient_user_id'), ['patient_user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_responsible_doctor_id'), ['responsible_doctor_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_patients_patient_user_id_users',
            'users',
            ['patient_user_id'],
            ['id'],
        )
        batch_op.create_foreign_key(
            'fk_patients_responsible_doctor_id_users',
            'users',
            ['responsible_doctor_id'],
            ['id'],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients') as batch_op:
        batch_op.drop_constraint(
            'fk_patients_responsible_doctor_id_users',
            type_='foreignkey',
        )
        batch_op.drop_constraint(
            'fk_patients_patient_user_id_users',
            type_='foreignkey',
        )
        batch_op.drop_index(batch_op.f('ix_patients_responsible_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_patients_patient_user_id'))
        batch_op.drop_column('responsible_doctor_id')
        batch_op.drop_column('patient_user_id')
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_encounter_code'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_doctor_id'), table_name='encounters')
    op.drop_table('encounters')
    # ### end Alembic commands ###
